#!/usr/bin/env python3
"""
apply-keys.sh — propagates API keys from ~/.theHarvester/api-keys.yaml to:
  - ~/.config/osint/keys.env      (bash exports — sourced at shell startup)
  - shodan CLI                     (shodan init KEY)
  - censys CLI                     (~/.config/censys/censys.cfg)
  - nuclei                         (~/.config/nuclei/nuclei-config.yaml)
  - ProjectDiscovery Cloud (pdcp)  (~/.pdcp/credentials.yaml)

Run this any time you update ~/.theHarvester/api-keys.yaml
"""
import sys
import os
import subprocess
from pathlib import Path

try:
    import yaml
except ImportError:
    subprocess.run([sys.executable, "-m", "pip", "install", "--quiet", "pyyaml"], check=True)
    import yaml

KEYS_YAML = Path.home() / ".theHarvester" / "api-keys.yaml"
ENV_OUT   = Path.home() / ".config" / "osint" / "keys.env"

def load_keys():
    with open(KEYS_YAML) as f:
        data = yaml.safe_load(f)
    return data.get("apikeys", {})

def get(keys, *path, default=""):
    d = keys
    for p in path:
        if not isinstance(d, dict):
            return default
        d = d.get(p, {})
    return d if isinstance(d, str) and d.strip() else default

def write_env(keys):
    ENV_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by apply-keys.sh — do not edit manually",
        "# Source: ~/.theHarvester/api-keys.yaml",
        "",
        "# ── Recon / scanning ─────────────────────────────────────────────────",
        f'export SHODAN_API_KEY="{get(keys, "shodan", "key")}"',
        f'export CENSYS_API_ID="{get(keys, "censys", "id")}"',
        f'export CENSYS_API_SECRET="{get(keys, "censys", "secret")}"',
        f'export SECURITY_TRAILS_KEY="{get(keys, "securityTrails", "key")}"',
        f'export SECURITYTRAILS_API_KEY="{get(keys, "securityTrails", "key")}"',  # alias for osint.sh
        f'export VIRUSTOTAL_API_KEY="{get(keys, "virustotal", "key")}"',
        f'export FULLHUNT_API_KEY="{get(keys, "fullhunt", "key")}"',
        f'export NETLAS_API_KEY="{get(keys, "netlas", "key")}"',
        f'export BEVIGIL_API_KEY="{get(keys, "bevigil", "key")}"',
        f'export BUFFEROVERUN_API_KEY="{get(keys, "bufferoverun", "key")}"',
        f'export CRIMINALIP_API_KEY="{get(keys, "criminalip", "key")}"',  # https://www.criminalip.io
        f'export ONYPHE_API_KEY="{get(keys, "onyphe", "key")}"',
        f'export WHOISXML_API_KEY="{get(keys, "whoisxml", "key")}"',
        f'export ZOOMEYE_API_KEY="{get(keys, "zoomeye", "key")}"',
        f'export HUNTERHOW_API_KEY="{get(keys, "hunterhow", "key")}"',
        f'export INTELX_API_KEY="{get(keys, "intelx", "key")}"',
        f'export INTELX_API_URL="https://free.intelx.io"',
        f'export VENACUS_API_KEY="{get(keys, "venacus", "key")}"',
        "",
        "# ── OSINT / people search ────────────────────────────────────────────",
        f'export HIBP_API_KEY="{get(keys, "haveibeenpwned", "key")}"',
        f'export HUNTER_API_KEY="{get(keys, "hunter", "key")}"',
        f'export ROCKETREACH_API_KEY="{get(keys, "rocketreach", "key")}"',
        f'export DEHASHED_API_KEY="{get(keys, "dehashed", "key")}"',
        f'export LEAKIX_API_KEY="{get(keys, "leakix", "key")}"',
        f'export TOMBA_API_KEY="{get(keys, "tomba", "key")}"',
        f'export TOMBA_API_SECRET="{get(keys, "tomba", "secret")}"',
        "",
        "# ── Dev / recon infrastructure ───────────────────────────────────────",
        f'export GITHUB_TOKEN="{get(keys, "github", "key")}"',
        f'export BING_API_KEY="{get(keys, "bing", "key")}"',
        f'export PDCP_API_KEY="{get(keys, "projectDiscovery", "key")}"',
        f'export PENTEST_TOOLS_API_KEY="{get(keys, "pentestTools", "key")}"',
        "",
        "# ── Wigle (set manually — encoded key) ───────────────────────────────",
        '# export WIGLE_API_KEY="your_encoded_key"',
        "",
        "# ── AbuseIPDB (set manually — not in theHarvester) ───────────────────",
        '# export ABUSEIPDB_API_KEY="your_key"',
    ]
    ENV_OUT.write_text("\n".join(lines) + "\n")
    print(f"  ✓ {ENV_OUT}")

def configure_shodan(keys):
    key = get(keys, "shodan", "key")
    if not key:
        print("  - shodan: no key set, skipping")
        return
    result = subprocess.run(["shodan", "init", key], capture_output=True, text=True)
    if result.returncode == 0:
        print("  ✓ shodan CLI configured")
    else:
        print(f"  ✗ shodan: {result.stderr.strip()}")

def configure_censys(keys):
    api_id     = get(keys, "censys", "id")
    api_secret = get(keys, "censys", "secret")
    if not api_id or not api_secret:
        print("  - censys: no id/secret set, skipping")
        return
    cfg_path = Path.home() / ".config" / "censys" / "censys.cfg"
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(
        f"[DEFAULT]\napi_id = {api_id}\napi_secret = {api_secret}\n"
    )
    print(f"  ✓ censys CLI configured ({cfg_path})")

def configure_nuclei(keys):
    pd_key = get(keys, "projectDiscovery", "key")
    if not pd_key:
        print("  - nuclei/pdcp: no ProjectDiscovery key set, skipping")
        return
    cfg_path = Path.home() / ".pdcp" / "credentials.yaml"
    cfg_path.parent.mkdir(parents=True, exist_ok=True)
    cfg_path.write_text(f"api-key: {pd_key}\n")
    print(f"  ✓ ProjectDiscovery Cloud credentials saved ({cfg_path})")

def main():
    if not KEYS_YAML.exists():
        print(f"ERROR: {KEYS_YAML} not found")
        sys.exit(1)

    keys = load_keys()
    filled = sum(1 for v in keys.values()
                 if isinstance(v, dict) and any(str(x).strip() for x in v.values() if x))
    total  = len(keys)
    print(f"\napply-keys — {filled}/{total} keys populated\n")

    print("Generating ~/.config/osint/keys.env ...")
    write_env(keys)

    print("Configuring shodan CLI ...")
    configure_shodan(keys)

    print("Configuring censys CLI ...")
    configure_censys(keys)

    print("Configuring nuclei / ProjectDiscovery Cloud ...")
    configure_nuclei(keys)

    print(f"\nDone. Re-source your shell or run:\n  source {ENV_OUT}\n")

if __name__ == "__main__":
    main()
