#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════╗
# ║  se_clickjacking.sh — Clickjacking Analysis                  ║
# ║  X-Frame-Options + CSP frame-ancestors on sensitive pages    ║
# ╚══════════════════════════════════════════════════════════════╝
set -uo pipefail

SCRIPT_NAME="se_clickjacking.sh"
SCRIPT_DESC="Clickjacking Analysis"

script_usage() {
    echo "Usage: ${SCRIPT_NAME} [OPTIONS]"
    echo ""
    echo "  Check X-Frame-Options and CSP frame-ancestors on sensitive"
    echo "  pages. Generate PoC HTML for frameable endpoints."
    echo "  VRT: Clickjacking max P4 (sensitive actions only)."
    echo ""
    echo "Options:"
    echo "  -u, --urls FILE        File with sensitive URLs (from Phase 1)"
    echo "  -o, --out DIR          Output directory (default: ./out)"
    echo "  -t, --threads N        Concurrency (default: 30)"
    echo "  -h, --help             Show this help"
}

LIB_DIR="$(cd "$(dirname "$0")/.." && pwd)"
source "${LIB_DIR}/lib.sh"
parse_common_args "$@"

phase_header "3" "$SCRIPT_DESC"

# ── Input resolution ──
urls_input="${URLS_FILE:-${OUT_DIR}/sensitive_urls.txt}"
findings_file="${OUT_DIR}/clickjack_findings.txt"
poc_dir="${OUT_DIR}/clickjack_pocs"
> "$findings_file"
mkdir -p "$poc_dir"

if [ ! -f "$urls_input" ] || [ ! -s "$urls_input" ]; then
    warn "No sensitive URLs found at ${urls_input} — skipping clickjacking"
    exit 0
fi

total=$(count_lines "$urls_input")
log "Testing ${total} URLs for clickjacking"

# ── Skip patterns (marketing/blog = not reportable) ──
skip_pattern='(blog|press|news|careers|about|legal|privacy|terms|faq|help/article|documentation|docs/|status\.)'

checked=0
frameable=0

while IFS= read -r url; do
    [ -z "$url" ] && continue

    # Skip non-sensitive pages
    if echo "$url" | grep -qiP "$skip_pattern"; then
        continue
    fi

    ((checked++)) || true

    # Fetch headers
    headers=$(curl -sk -D- -o /dev/null --connect-timeout 5 --max-time 10 "${HUNT_UA_CURL[@]}" "$url" 2>/dev/null || true)
    [ -z "$headers" ] && continue

    # Check X-Frame-Options
    xfo=$(echo "$headers" | grep -i '^X-Frame-Options:' | head -1 | tr -d '\r')

    # Check CSP frame-ancestors
    csp=$(echo "$headers" | grep -i '^Content-Security-Policy:' | head -1 | tr -d '\r')
    frame_ancestors=""
    if [ -n "$csp" ]; then
        frame_ancestors=$(echo "$csp" | grep -oP "frame-ancestors\s+[^;]+" | head -1)
    fi

    # Determine if frameable
    is_frameable=false
    reason=""

    if [ -z "$xfo" ] && [ -z "$frame_ancestors" ]; then
        is_frameable=true
        reason="NO_XFO_NO_CSP"
    elif [ -n "$frame_ancestors" ]; then
        # frame-ancestors 'self' or 'none' blocks framing
        if echo "$frame_ancestors" | grep -qiP "(frame-ancestors\s+'none')"; then
            reason="BLOCKED_BY_CSP_NONE"
        elif echo "$frame_ancestors" | grep -qiP "(frame-ancestors\s+'self'\s*$)"; then
            reason="BLOCKED_BY_CSP_SELF"
        elif echo "$frame_ancestors" | grep -qiP '\*'; then
            is_frameable=true
            reason="CSP_WILDCARD"
        else
            reason="CSP_RESTRICTED"
        fi
    elif [ -n "$xfo" ]; then
        if echo "$xfo" | grep -qi "DENY"; then
            reason="BLOCKED_BY_XFO_DENY"
        elif echo "$xfo" | grep -qi "SAMEORIGIN"; then
            reason="BLOCKED_BY_XFO_SAMEORIGIN"
        elif echo "$xfo" | grep -qi "ALLOW-FROM"; then
            # ALLOW-FROM is deprecated and ignored by modern browsers
            is_frameable=true
            reason="XFO_ALLOW_FROM_DEPRECATED"
        fi
    fi

    if $is_frameable; then
        ((frameable++)) || true

        # Classify page sensitivity
        sensitivity="LOW"
        if echo "$url" | grep -qiP '(login|signin|auth|password|payment|transfer|settings|admin|account)'; then
            sensitivity="HIGH"
        elif echo "$url" | grep -qiP '(register|signup|profile|preferences|consent)'; then
            sensitivity="MEDIUM"
        fi

        echo "[P4:CLICKJACK:FRAMEABLE] ${url} | ${reason} | sensitivity:${sensitivity}" >> "$findings_file"

        # Generate PoC HTML
        safe_name=$(echo "$url" | sed 's|https\?://||;s|[/:]|_|g' | head -c 60)
        cat > "${poc_dir}/${safe_name}.html" << POCEOF
<!DOCTYPE html>
<html>
<head><title>Clickjacking PoC — ${url}</title></head>
<body>
<h2>Clickjacking PoC</h2>
<p>Target: <code>${url}</code></p>
<p>Reason: ${reason}</p>
<div style="position:relative;width:800px;height:600px;">
    <iframe src="${url}" style="width:100%;height:100%;opacity:0.3;position:absolute;top:0;left:0;z-index:2;" sandbox="allow-forms allow-scripts allow-same-origin"></iframe>
    <div style="position:absolute;top:50%;left:50%;z-index:1;font-size:24px;color:red;">
        Click here to win!
    </div>
</div>
<hr>
<p><em>Generated by social.sh — se_clickjacking.sh</em></p>
</body>
</html>
POCEOF
    fi
done < "$urls_input"

# ── Nuclei clickjacking templates ──
if check_tool "nuclei" 2>/dev/null && [ -s "$urls_input" ]; then
    info "Running nuclei clickjacking templates..."
    nuclei_cj="${OUT_DIR}/nuclei_clickjack.txt"
    nuclei -l "$urls_input" -tags clickjacking -silent \
        "${HUNT_UA_ARGS[@]}" 2>/dev/null > "$nuclei_cj" || true
    if [ -s "$nuclei_cj" ]; then
        cat "$nuclei_cj" >> "$findings_file"
        log "Nuclei clickjacking findings: $(count_lines "$nuclei_cj")"
    fi
fi

# ── Summary ──
sort -u -o "$findings_file" "$findings_file"
log "Checked: ${checked} URLs"
log "Frameable: ${frameable}"
log "PoC files: ${poc_dir}/"
finding_count=$(count_lines "$findings_file")
log "Total clickjacking findings: ${finding_count}"
if [ "$finding_count" -gt 0 ]; then
    warn "Frameable sensitive pages found:"
    grep "sensitivity:HIGH" "$findings_file" || true
fi
